# Basic
title: jacky
subtitle: A technique blog for jacky
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: here are my artitles about work(embeded system develop, docker, etc.) and life(cook, hiking)
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://github.com/jialinxie"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/jialinxie'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: null
    github: github.com/jialinxie
    twitter: null
    gplus: 107108267983477358170
    mail: lin990033@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
